#!/usr/bin/env zsh

# ~~~~~~~~~~~~~~~~~~~

plugin_source_git() {
	ZSH_PLUGIN="$HOME/.zsh_plugins/$2/$3"
	[ ! -f "$ZSH_PLUGIN" ] && git clone "git@github.com:$1/$2.git" "$HOME/.zsh_plugins/$2"
	source "$ZSH_PLUGIN"
}

# Plugins
plugin_source_git "zsh-users" "zsh-autosuggestions" "zsh-autosuggestions.zsh"
plugin_source_git "zsh-users" "zsh-history-substring-search" "zsh-history-substring-search.zsh"
plugin_source_git "zsh-users" "zsh-syntax-highlighting" "zsh-syntax-highlighting.zsh"
plugin_source_git "agkozak" "zsh-z" "zsh-z.plugin.zsh"

# bindings
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '^[[3~' delete-char

# autocompletes
fpath=("$HOME/.zsh/completion" $fpath)
zsh-completion kubectl
zsh-completion crie
zsh-completion podman
zsh-completion docker

if [ $commands[brew] ]; then
  fpath=("$(brew --prefix)/share/zsh/site-functions" $fpath)
fi

# autocomplete load
autoload -U compinit
compinit

# alias
alias k="kubectl"
alias _="sudo"

# easy jump into a container
alias boop="docker run --rm -it"
alias ubuntu="boop ubuntu"
alias centos="boop centos"
alias debian="boop debian"
alias alpine="boop alpine"
alias fedora="boop fedora"
alias suse="boop opensuse/leap bash"

alias watch-logs="dmesg -THw"

# git
alias nuke="git reset --hard HEAD && git clean -df" # -x

# project Init
alias projinit="mkdir -p script && touch LICENSE README.md CONTRIBUTING.md script/test script/bootstrap"

# cmake
alias build="cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Release -GNinja && cmake --build build"

# terraform
alias tfgraph="terraform graph | dot -Tps -o graph.ps"

# update
up_cmd=""
if [ $commands[apt] ]; then
	up_cmd="_ apt update;_ apt -y full-upgrade;_ apt -y autoremove;$up_cmd"
fi
if [ $commands[brew] ]; then
	up_cmd="brew update;brew upgrade;brew cleanup;$up_cmd"
fi
if [ $commands[flatpak] ]; then
	up_cmd="flatpak update;$up_cmd"
fi
alias up="$up_cmd"

# history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
setopt sharehistory
setopt incappendhistory

alias install-vim="wget -O ~/.vimrc https://raw.githubusercontent.com/mathiasbynens/dotfiles/main/.vimrc ; mkdir -p ~/.vim/swaps ~/.vim/backups ~/.vim/undo ~/.vim/colors; wget -O ~/.vim/colors/solarized.vim https://raw.githubusercontent.com/mathiasbynens/dotfiles/main/.vim/colors/solarized.vim"

if [ ! $commands[starship] ]; then
	set -x
        curl -sS https://starship.rs/install.sh | sh
	set +x
fi
export STARSHIP_CONFIG="$HOME/.starship.toml"
eval "$(starship init zsh)"
